#pragma once

#include "math-parse.h"

struct parser_stack_value {
    int state;
    struct token value;
};

struct parser_stack {
    struct parser_stack_value value;
    struct parser_stack *next;
};

enum parse_table_action { ERROR = 0, ACCEPT, SHIFT, REDUCE };

typedef void (*reduce_rule)(struct parser_stack **stack);

union parse_table_value {
    int next_state;
    reduce_rule rule;
};

struct parse_table_item {
    enum parse_table_action action;
    union parse_table_value value;
};

void reduce_rule_1(struct parser_stack **stack);
void reduce_rule_2(struct parser_stack **stack);
void reduce_rule_3(struct parser_stack **stack);
void reduce_rule_4(struct parser_stack **stack);
void reduce_rule_5(struct parser_stack **stack);
void reduce_rule_6(struct parser_stack **stack);
void reduce_rule_7(struct parser_stack **stack);

#define STATE_COUNT 28
const struct parse_table_item parse_table[STATE_COUNT][TOKEN_TYPE_COUNT] = {
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 3}},
     {ERROR},
     {SHIFT, {.next_state = 4}},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 1}},
     {SHIFT, {.next_state = 2}}},
    {{SHIFT, {.next_state = 5}},
     {SHIFT, {.next_state = 6}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {ACCEPT},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_3}},
     {REDUCE, {.rule = reduce_rule_3}},
     {SHIFT, {.next_state = 7}},
     {ERROR},
     {SHIFT, {.next_state = 8}},
     {ERROR},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_3}},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_6}},
     {REDUCE, {.rule = reduce_rule_6}},
     {REDUCE, {.rule = reduce_rule_6}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_6}},
     {ERROR},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_6}},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 11}},
     {ERROR},
     {SHIFT, {.next_state = 12}},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 9}},
     {SHIFT, {.next_state = 10}}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 3}},
     {ERROR},
     {SHIFT, {.next_state = 4}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 13}}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 3}},
     {ERROR},
     {SHIFT, {.next_state = 4}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 14}}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 3}},
     {ERROR},
     {SHIFT, {.next_state = 4}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
    {SHIFT, {.next_state = 15}}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 3}},
     {ERROR},
     {SHIFT, {.next_state = 4}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
    {SHIFT, {.next_state = 16}}},
    {
     {SHIFT, {.next_state = 18}},
     {SHIFT, {.next_state = 19}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 17}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     },
    {{REDUCE, {.rule = reduce_rule_3}},
     {REDUCE, {.rule = reduce_rule_3}},
     {SHIFT, {.next_state = 20}},
     {ERROR},
     {SHIFT, {.next_state = 21}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_3}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_6}},
     {REDUCE, {.rule = reduce_rule_6}},
     {REDUCE, {.rule = reduce_rule_6}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_6}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_6}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 11}},
     {ERROR},
     {SHIFT, {.next_state = 12}},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 22}},
     {SHIFT, {.next_state = 10}}},
    {{REDUCE, {.rule = reduce_rule_1}},
     {REDUCE, {.rule = reduce_rule_1}},
     {SHIFT, {.next_state = 7}},
     {ERROR},
     {SHIFT, {.next_state = 8}},
     {ERROR},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_1}},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_2}},
     {REDUCE, {.rule = reduce_rule_2}},
     {SHIFT, {.next_state = 7}},
     {ERROR},
     {SHIFT, {.next_state = 8}},
     {ERROR},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_2}},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_4}},
     {REDUCE, {.rule = reduce_rule_4}},
     {REDUCE, {.rule = reduce_rule_4}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_4}},
     {ERROR},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_4}},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_5}},
     {REDUCE, {.rule = reduce_rule_5}},
     {REDUCE, {.rule = reduce_rule_5}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_5}},
     {ERROR},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_5}},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_7}},
     {REDUCE, {.rule = reduce_rule_7}},
     {REDUCE, {.rule = reduce_rule_7}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_7}},
     {ERROR},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_7}},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 11}},
     {ERROR},
     {SHIFT, {.next_state = 12}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 23}}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 11}},
     {ERROR},
     {SHIFT, {.next_state = 12}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 24}}},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 11}},
     {ERROR},
     {SHIFT, {.next_state = 12}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
    {SHIFT, {.next_state = 25}},},
    {{ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 11}},
     {ERROR},
     {SHIFT, {.next_state = 12}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
    	 {SHIFT, {.next_state = 26}}},
    {{SHIFT, {.next_state = 18}},
     {SHIFT, {.next_state = 19}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR},
     {SHIFT, {.next_state = 27}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}},
    {{REDUCE, {.rule = reduce_rule_1}},
     {REDUCE, {.rule = reduce_rule_1}},
     {SHIFT, {.next_state = 20}},
     {ERROR},
     {SHIFT, {.next_state = 21}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_1}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}                              },
    {{REDUCE, {.rule = reduce_rule_2}},
     {REDUCE, {.rule = reduce_rule_2}},
     {SHIFT, {.next_state = 20}},
     {ERROR},
     {SHIFT, {.next_state = 21}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_2}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}                              },
    {{REDUCE, {.rule = reduce_rule_4}},
     {REDUCE, {.rule = reduce_rule_4}},
     {REDUCE, {.rule = reduce_rule_4}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_4}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_4}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}                              },
    {{REDUCE, {.rule = reduce_rule_5}},
     {REDUCE, {.rule = reduce_rule_5}},
     {REDUCE, {.rule = reduce_rule_5}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_5}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_5}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}                              },
    {{REDUCE, {.rule = reduce_rule_7}},
     {REDUCE, {.rule = reduce_rule_7}},
     {REDUCE, {.rule = reduce_rule_7}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_7}},
     {ERROR},
     {REDUCE, {.rule = reduce_rule_7}},
     {ERROR},
     {ERROR},
     {ERROR},
     {ERROR}                              }
};
